#!/bin/bash
# Run Hidden Markov Model to  PRO-seq to make bam and bedgraph files

if [ $# -lt 2 ]; then
	echo -e "Usage:\t proseq-align [options] -f <fastq> -r <reference genome>"
	echo -e "Options:"
	echo -e "\t-a\talinger (STAR/BOWTIE; default = STAR)"
	echo -e "\t-b\toutput filename base (default = proseq.out)"
	exit
fi

SCRIPTDIR="~/Work/shared/script/"
ALINGER=star
BASE="proseq.out"

while [[ $# -ge 1 ]]; do
	key="$1"
	case $key in
		-a)
		BAM="$2"
		shift
		;;
		-b)
		BED="$2"
		shift
		;;
		-bin)
		BIN="$2"
		shift
		;;
		-win)
		WIN="$2"
		shift
		;;
		--default)
		;;
		*)
		;;
	esac
	shift
done

# Cut out adapter sequences if any
cutadapt -a TGGAATTCTCGGGTGCCAAGG $1 > "${1%.*}".trim.fastq 
# Tagging UMI to the sequence ID
~/Work/shared/script/umi-split-fastq.sh "${1%.*}".trim.fastq

# Alignemnt to the reference genome
~/Work/bin/star --genomeDir ~/Work/shared/ref/hg38 --readFilesIn "${1%.*}".trim.UMItag.fastq --outFilterMultimapNmax 1 --runThreadN 8

# Collapse same UMIs at the same mapped positions 
~/Work/shared/script/umi-collapse.sh Aligned.out.sam


